import { type Property, type Investment, type SwapTransaction } from './types';

export const SOL_TO_USD = 170.52;

export const CITIES = ['Алматы', 'Астана', 'Шымкент'] as const;

export const MOCK_PROPERTIES: Property[] = [
    {
        id: '1',
        title: 'ЖК "Солнечный город" — 2-комнатная квартира',
        description:
            'Современная квартира в новом жилом комплексе премиум-класса с видом на горы. Продуманная планировка, качественная отделка, подземный паркинг. Идеальный объект для инвестиций с высокой арендной доходностью.',
        images: [
            { url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop', alt: 'Фасад ЖК' },
            { url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop', alt: 'Интерьер' },
            { url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop', alt: 'Кухня' },
        ],
        location: { city: 'Алматы', address: 'ул. Аль-Фараби 77/8', district: 'Бостандыкский' },
        price: { totalSOL: 850, pricePerToken: 0.85 },
        tokensTotal: 1000,
        tokensSold: 782,
        roi: 12.5,
        status: 'active',
        propertyType: 'apartment',
        area: 78,
        rooms: 2,
        floor: 14,
        totalFloors: 25,
        yearBuilt: 2025,
        developer: 'BI Group',
        oracleVerified: true,
        createdAt: '2026-01-15',
    },
    {
        id: '2',
        title: 'ЖК "Expo Residence" — 3-комнатная квартира',
        description:
            'Просторная квартира рядом с EXPO. Развитая инфраструктура, рядом школы, торговые центры, метро. Высокий спрос на аренду среди экспатов и госслужащих.',
        images: [
            { url: 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=800&h=600&fit=crop', alt: 'Здание' },
            { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop', alt: 'Гостиная' },
            { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop', alt: 'Спальня' },
        ],
        location: { city: 'Астана', address: 'пр. Мангилик Ел 42', district: 'Есильский' },
        price: { totalSOL: 1200, pricePerToken: 1.2 },
        tokensTotal: 1000,
        tokensSold: 456,
        roi: 10.8,
        status: 'active',
        propertyType: 'apartment',
        area: 105,
        rooms: 3,
        floor: 8,
        totalFloors: 18,
        yearBuilt: 2024,
        developer: 'Bazis-A',
        oracleVerified: true,
        createdAt: '2026-02-01',
    },
    {
        id: '3',
        title: 'ЖК "Green Park" — Студия',
        description:
            'Компактная студия в экологичном ЖК с зелёной территорией и собственным парком. Отличный вариант для старта инвестиций — низкий порог входа и стабильный арендный спрос.',
        images: [
            { url: 'https://images.unsplash.com/photo-1574362848149-11496d93a7c7?w=800&h=600&fit=crop', alt: 'Студия' },
            { url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop', alt: 'Интерьер' },
        ],
        location: { city: 'Алматы', address: 'ул. Тимирязева 28Б', district: 'Медеуский' },
        price: { totalSOL: 350, pricePerToken: 0.35 },
        tokensTotal: 1000,
        tokensSold: 1000,
        roi: 14.2,
        status: 'funded',
        propertyType: 'apartment',
        area: 38,
        rooms: 1,
        floor: 6,
        totalFloors: 12,
        yearBuilt: 2025,
        developer: 'Alshinbayev Group',
        oracleVerified: true,
        createdAt: '2025-11-20',
    },
    {
        id: '4',
        title: 'ЖК "Capital Tower" — 2-комнатная',
        description:
            'Квартира бизнес-класса в самом центре столицы. Панорамное остекление, консьерж-сервис, фитнес-центр на территории. Престижное расположение обеспечивает высокую капитализацию.',
        images: [
            { url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&h=600&fit=crop', alt: 'Башня' },
            { url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop', alt: 'Квартира' },
        ],
        location: { city: 'Астана', address: 'ул. Сыганак 18/1', district: 'Есильский' },
        price: { totalSOL: 1500, pricePerToken: 1.5 },
        tokensTotal: 1000,
        tokensSold: 150,
        roi: 9.5,
        status: 'active',
        propertyType: 'apartment',
        area: 92,
        rooms: 2,
        floor: 22,
        totalFloors: 30,
        yearBuilt: 2026,
        developer: 'BI Group',
        oracleVerified: false,
        createdAt: '2026-03-10',
    },
    {
        id: '5',
        title: 'ЖК "Almaty Towers" — 1-комнатная',
        description:
            'Уютная однушка в новостройке рядом с горным кластером. Чистый воздух, рядом парки и горнолыжные курорты. Высокий спрос на краткосрочную аренду от туристов.',
        images: [
            { url: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800&h=600&fit=crop', alt: 'ЖК' },
            { url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop', alt: 'Вид' },
        ],
        location: { city: 'Алматы', address: 'мкр. Горный Гигант 15', district: 'Медеуский' },
        price: { totalSOL: 500, pricePerToken: 0.5 },
        tokensTotal: 1000,
        tokensSold: 678,
        roi: 13.1,
        status: 'active',
        propertyType: 'apartment',
        area: 52,
        rooms: 1,
        floor: 10,
        totalFloors: 16,
        yearBuilt: 2025,
        developer: 'Kurylys Company',
        oracleVerified: true,
        createdAt: '2026-01-28',
    },
    {
        id: '6',
        title: 'ЖК "Sky Garden" — 4-комнатная пентхаус',
        description:
            'Элитный пентхаус с террасой на крыше. Два уровня, собственная зона барбекю, панорамный вид на весь город. Эксклюзивный инвестиционный объект для крупных инвесторов.',
        images: [
            { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&h=600&fit=crop', alt: 'Пентхаус' },
            { url: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop', alt: 'Терраса' },
        ],
        location: { city: 'Алматы', address: 'пр. Достык 132', district: 'Медеуский' },
        price: { totalSOL: 3000, pricePerToken: 3.0 },
        tokensTotal: 1000,
        tokensSold: 89,
        roi: 8.7,
        status: 'upcoming',
        propertyType: 'apartment',
        area: 210,
        rooms: 4,
        floor: 25,
        totalFloors: 25,
        yearBuilt: 2026,
        developer: 'Premium Stroy',
        oracleVerified: false,
        createdAt: '2026-03-20',
    },
    {
        id: '7',
        title: 'ЖК "Nomad City" — 2-комнатная',
        description:
            'Современный комплекс в быстрорастущем районе. Рядом IT-парк, международные компании, транспортные хабы. Идеально для долгосрочной аренды.',
        images: [
            { url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&h=600&fit=crop', alt: 'Фасад' },
            { url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&h=600&fit=crop', alt: 'Планировка' },
        ],
        location: { city: 'Астана', address: 'ул. Кабанбай Батыра 62', district: 'Алматинский' },
        price: { totalSOL: 700, pricePerToken: 0.7 },
        tokensTotal: 1000,
        tokensSold: 923,
        roi: 11.4,
        status: 'active',
        propertyType: 'apartment',
        area: 72,
        rooms: 2,
        floor: 5,
        totalFloors: 14,
        yearBuilt: 2024,
        developer: 'Bazis-A',
        oracleVerified: true,
        createdAt: '2025-12-05',
    },
    {
        id: '8',
        title: 'ЖК "Shymkent Plaza" — 3-комнатная',
        description:
            'Первый токенизированный объект в Шымкенте. Новый ЖК в центре города с отличной транспортной доступностью. Растущий рынок с высоким потенциалом.',
        images: [
            { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop', alt: 'Дом' },
            { url: 'https://images.unsplash.com/photo-1600573472556-e636c2acda9e?w=800&h=600&fit=crop', alt: 'Двор' },
        ],
        location: { city: 'Шымкент', address: 'ул. Байтурсынова 15', district: 'Аль-Фарабийский' },
        price: { totalSOL: 420, pricePerToken: 0.42 },
        tokensTotal: 1000,
        tokensSold: 312,
        roi: 15.0,
        status: 'active',
        propertyType: 'apartment',
        area: 85,
        rooms: 3,
        floor: 3,
        totalFloors: 9,
        yearBuilt: 2025,
        developer: 'Shymkent Kurylys',
        oracleVerified: true,
        createdAt: '2026-02-14',
    },
    {
        id: '9',
        title: 'ЖК "Botanical" — 1-комнатная smart-квартира',
        description:
            'Smart-квартира с системой умного дома. Энергоэффективное здание, зелёная сертификация. Низкие коммунальные расходы повышают чистую доходность аренды.',
        images: [
            { url: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop', alt: 'Smart квартира' },
            { url: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800&h=600&fit=crop', alt: 'Технологии' },
        ],
        location: { city: 'Алматы', address: 'ул. Ботаническая 12', district: 'Бостандыкский' },
        price: { totalSOL: 280, pricePerToken: 0.28 },
        tokensTotal: 1000,
        tokensSold: 1000,
        roi: 13.8,
        status: 'completed',
        propertyType: 'apartment',
        area: 42,
        rooms: 1,
        floor: 4,
        totalFloors: 10,
        yearBuilt: 2024,
        developer: 'Green Build KZ',
        oracleVerified: true,
        createdAt: '2025-08-10',
    },
    {
        id: '10',
        title: 'ЖК "Central Park" — 2-комнатная',
        description:
            'Квартира в сердце делового района с видом на Центральный парк. Пешая доступность к офисам, ресторанам и развлечениям. Стабильный арендный доход от бизнес-аудитории.',
        images: [
            { url: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&h=600&fit=crop', alt: 'Вид' },
            { url: 'https://images.unsplash.com/photo-1600607687644-c7171b42498f?w=800&h=600&fit=crop', alt: 'Зал' },
        ],
        location: { city: 'Астана', address: 'пр. Республики 18', district: 'Сарыаркинский' },
        price: { totalSOL: 950, pricePerToken: 0.95 },
        tokensTotal: 1000,
        tokensSold: 567,
        roi: 10.2,
        status: 'active',
        propertyType: 'apartment',
        area: 88,
        rooms: 2,
        floor: 15,
        totalFloors: 22,
        yearBuilt: 2025,
        developer: 'Capital Group',
        oracleVerified: true,
        createdAt: '2026-01-05',
    },
];

export const MOCK_INVESTMENTS: Investment[] = [
    {
        id: 'inv-1',
        propertyId: '1',
        propertyTitle: 'ЖК "Солнечный город" — 2-комнатная квартира',
        propertyImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop',
        amountSOL: 25.5,
        tokensReceived: 30,
        date: '2026-02-10',
        roi: 12.5,
        status: 'active',
    },
    {
        id: 'inv-2',
        propertyId: '5',
        propertyTitle: 'ЖК "Almaty Towers" — 1-комнатная',
        propertyImage: 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800&h=600&fit=crop',
        amountSOL: 15.0,
        tokensReceived: 30,
        date: '2026-02-28',
        roi: 13.1,
        status: 'active',
    },
    {
        id: 'inv-3',
        propertyId: '9',
        propertyTitle: 'ЖК "Botanical" — 1-комнатная smart-квартира',
        propertyImage: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&h=600&fit=crop',
        amountSOL: 8.4,
        tokensReceived: 30,
        date: '2025-09-15',
        roi: 13.8,
        status: 'completed',
    },
];

export const MOCK_SWAP_HISTORY: SwapTransaction[] = [
    { id: 'sw-1', inputToken: 'USDT', inputAmount: 500, outputAmount: 2.93, rate: 170.52, date: '2026-03-25', status: 'completed' },
    { id: 'sw-2', inputToken: 'USDS', inputAmount: 1000, outputAmount: 5.86, rate: 170.65, date: '2026-03-20', status: 'completed' },
    { id: 'sw-3', inputToken: 'USDT', inputAmount: 200, outputAmount: 1.17, rate: 170.94, date: '2026-03-15', status: 'completed' },
];

export const DEFAULT_WALLET = {
    address: '7nYkPnMKrDJqLwkGbcoaYHFb4949bpNc5DzFXBTfcKU1',
    balance: 125.5,
    isConnected: true,
    tokenBalances: {
        USDT: 2500.0,
        USDS: 1800.0,
    },
};
